Stats/scoreboard
CU-CSCI3308-Fall2023/Wordle pull request #56
Opened 2023-12-04 01:11 UTC by nthnns

added scoreboard.ejs
added stats.css
modified auth.ts for login and register
modified login.ejs and register.ejs to add in error messages

2023-12-04 02:01 UTC, feRpicoral requested changes
Some extra comments other than the specific ones I left:

![image](https://github.com/CU-CSCI3308-Fall2023/Wordle/assets/30874402/7d5056cf-1781-4d37-944a-8ea06892bf63)

1) We can improve the design of the table a little instead of just using a plain HTML table

2) Add some margin to the x axis so it doesn't stretch all the way. I recommend using Bootstrap grid classes

3) We need a different style to show that the very first row is you (the logged in user). 

4) You are not displaying the other columns, only the position and username (see screenshot)

2023-12-04 02:01 UTC, feRpicoral commented on app/src/ui/views/game.ejs
You didn't change anything on this file - revert these changes. (this was likely caused by your IDE having auto-formatting turned on somewhere)

2023-12-04 02:01 UTC, feRpicoral commented on app/src/public/css/stats.css
> +    background: #2e2e2e;
The rest of the app is not in dark more - I don't think this page should be

2023-12-04 02:01 UTC, feRpicoral commented on app/src/public/css/stats.css
> +* {
Do not use `*`. Use the proper selector for what you want to style

2023-12-04 02:02 UTC, feRpicoral commented on app/src/public/css/stats.css
Rename this file to `scoreboard.css` for the sake of consistency

2023-12-05 16:10 UTC, feRpicoral commented on app/src/public/css/scoreboard.css
> +}
Don't do this - you are overriding a bootstrap class. Create your class (or use bootstrap's `text-center` class, that is, where you have `class="col-sm-2"` change it to `class="col-sm-2 text-center"`)

2023-12-05 16:13 UTC, feRpicoral commented on app/src/public/css/scoreboard.css
> +.container {
`container` is a bootstrap class. Change the name to avoid conflicts with your stuff

2023-12-06 06:34 UTC, nthnns commented on app/src/public/css/scoreboard.css
added css changes

2023-12-06 06:34 UTC, nthnns commented on app/src/routers/scoreboard.ts
This made it look better when I displayed the APPG

2023-12-06 06:35 UTC, nthnns commented on app/src/ui/views/scoreboard.ejs
went back to a table but I made it cleaner than before
<img width="1080" alt="Screenshot 2023-12-05 at 11 28 27 PM" src="https://github.com/CU-CSCI3308-Fall2023/Wordle/assets/111916840/13ce044c-4e85-4024-9657-27a0839489bf">

2023-12-06 08:25 UTC, closed without merging